site_name: netboot.ipfs
site_description: netboot.ipfs uses iPXE and IPFS to network boot Operating System installers and utilities from an easy to use menu.
site_author: netboot.ipfs
site_url: https://netboot.devtty.eu
repo_url: https://github.com/magik6k/netboot.xyz
copyright: © 2017 <a href="https://twitter.com/@ntonym">Antony Messerli</a>, <a href="https://twitter.com/magik6k">Łukasz Magiera</a>
docs_dir: docs
pages:
- Home: 'index.md'
- Boot from...:
    - 'ISO': 'boot-iso.md'
    - 'TFTP': 'boot-tftp.md'
    - 'USB': 'boot-usb.md'
    - 'VMware': 'boot-vmware.md'
- FAQ: 'faq.md'
theme: yeti
use_directory_urls: false
